openapi: 3.0.3
info:
    title: Bank Transactions API
    description: API for managing bank transactions
    contact:
        email: christellecharlesalfred56@gmail.com
    license:
        name: Christelle
    version: 1.0.0
servers:
    - url: http://localhost:3000/api
      description: Local server

tags:
    - name: Transactions
      description: Operations related to transactions

paths:
    /transactions/current-month:
        get:
            tags:
                - Transactions
            summary: Get all transactions for the current month
            description: Retrieve a list of all transactions for the current month, grouped by account.
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: A list of transactions grouped by account
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        accountId:
                                            type: string
                                            description: The ID of the account
                                        transactions:
                                            type: array
                                            items:
                                                $ref: "#/components/schemas/Transaction"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

    /transactions/{transactionId}:
        get:
            tags:
                - Transactions
            summary: Get details of a specific transaction
            description: Retrieve the details of a specific transaction by transaction ID.
            security:
                - bearerAuth: []
            parameters:
                - name: transactionId
                  in: path
                  required: true
                  description: The ID of the transaction to retrieve
                  schema:
                      type: string
            responses:
                "200":
                    description: Details of the transaction
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Transaction"
                "404":
                    description: Transaction not found
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

        put:
            tags:
                - Transactions
            summary: Update a transaction
            description: Update information about a specific transaction by transaction ID.
            security:
                - bearerAuth: []
            parameters:
                - name: transactionId
                  in: path
                  required: true
                  description: The ID of the transaction to update
                  schema:
                      type: string
            requestBody:
                description: Updated transaction object
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Transaction"
            responses:
                "200":
                    description: Transaction updated successfully
                "400":
                    description: Bad Request
                "404":
                    description: Transaction not found
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

        patch:
            tags:
                - Transactions
            summary: Partially update (clear) specific fields of a transaction
            description: Partially update information about a specific transaction by transaction ID.
            security:
                - bearerAuth: []
            parameters:
                - name: transactionId
                  in: path
                  required: true
                  description: The ID of the transaction to update
                  schema:
                      type: string
            requestBody:
                description: Fields to clear in the transaction object
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                fields:
                                    type: array
                                    items:
                                        type: string
                                    description: List of fields to clear
            responses:
                "200":
                    description: Transaction fields updated successfully
                "400":
                    description: Bad Request
                "404":
                    description: Transaction not found
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        Transaction:
            type: object
            properties:
                id:
                    type: string
                    description: The ID of the transaction
                accountId:
                    type: string
                    description: The ID of the account associated with the transaction
                amount:
                    type: number
                    format: float
                    description: The amount of the transaction
                date:
                    type: string
                    format: date
                    description: The date of the transaction
                description:
                    type: string
                    description: A description of the transaction
                category:
                    type: string
                    description: The category of the transaction
                userId:
                    type: string
                    description: The ID of the user who owns the transaction
